[package]
name = "raybird"
version = "0.1.0"
authors = ["Chris Pearce <christopher.james.pearce@gmail.com>"]
edition = "2018"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "tracer_bench"
harness = false

[dependencies]
nalgebra = "0.18.0"
rand = "0.6.5"